name: Close inactive issues and PRs
on:
  schedule:
    - cron: "30 1 * * *"

jobs:
  close-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v9
        with:
          days-before-issue-stale: 90
          days-before-issue-close: 30
          stale-issue-label: "stale"
          stale-issue-message: "This issue is stale because it has been open for 90 days with no activity. Remove stale label or comment or this will be closed in 30 days."
          close-issue-message: "This issue was closed because it has been inactive for 30 days since being marked as stale. Please leave a comment tagging an assigned team member if you need this issue to be reopened, and we will be happy to investigate. Thank you!"
          days-before-pr-stale: 90
          days-before-pr-close: 30
          stale-pr-message: "This pull request is stale because it has been open for 90 days with no activity. Remove stale label or comment or this will be closed in 30 days."
          close-pr-message: "This pull request was closed because it has been inactive for 30 days since being marked as stale."
          exempt-assignees: iTanken
          operations-per-run: 500
          repo-token: ${{ secrets.GITHUB_TOKEN }}
